### PR TITLE
fix(editor): code editor page down/up key scroll issue fixed

### LINKED ISSUE #224: code editor page down/up scroll doesn't work properly
**Describe the bug**
When you try to scroll up/down in any generated code, it overlaps the whole page and breaks ui

**To Reproduce**
1. Click Code Generation Button
2. Scroll any code file which has enough content to scroll. Scroll using page up or page down button.  Then you will see it breaks the whole UI.

**Expected behavior**
It should scroll properly using page up and down button

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [72]

### PR DESCRIPTION
**Pull request by sumitparakh**
Closes #224

### CODE REVIEW

**Comment by manekinekko** [comment]
I think the issue is still present!
image

**Comment by sumitparakh** [comment]
> I think the issue is still present!
> image

Weird. I tested it in Chrome 72 & 69 and it worked.  Earlier I've used scrollBy function which seem to have [less compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy#Browser_Compatibility)  so i used scrollTop property now. Please check now @manekinekko .

File: packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts [hunk 1]
```diff
@@ -192,4 +193,23 @@ export class EditorContainerComponent implements OnInit, AfterContentInit {
   updateState() {
     this.store.dispatch(new CodeGen(this.codeSetting.kind, this.codeSetting.content, this.codeSetting.buttons));
   }
+
+  simulateContentEditorScroll($event) {
+    const keyCode = $event.keyCode || $event.charCode || $event.which;
+    const scroll = Math.round(0.9 * this.codeEditor.nativeElement.clientHeight);
+
+    // Page Down
+    if (keyCode === 34 || $event.key === 'PageDown' || $event.code === 'PageDown') {
```
Comment (Jefiozie) [inline packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts]: Instead of using the `numbers` we could use the `@angular/cdk/keycodes`.
This way we can just reference the variables (made small example below):

```
import { PAGE_DOWN  } from '@angular/cdk/keycodes';

 if (keyCode === PAGE_DOWN   || $event.key === 'PageDown' || $event.code === 'PageDown')

```


What do you think about this @sumitparakh?

Comment (manekinekko) [reply packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts]: if we wanna do it the full angular way, we can use HostLiesterners

**Comment by manekinekko** [comment]
@sumitparakh Here with a zoom of 175%

image

File: packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts (hunk 1 above)
Comment (sumitparakh) [reply packages/xlayers/src/app/editor/code-editor/editor-container/editor-container.component.ts]: > Instead of using the `numbers` we could use the `@angular/cdk/keycodes`.
> This way we can just reference the variables (made small example below):
> 
> ```
> import { PAGE_DOWN  } from '@angular/cdk/keycodes';
> 
>  if (keyCode === PAGE_DOWN   || $event.key === 'PageDown' || $event.code === 'PageDown')
> ```
> What do you think about this @sumitparakh?

@Jefiozie . Yeah. This is better option. Thanks. I've just updated my code.

**Comment by sumitparakh** [comment]
> @sumitparakh Here with a zoom of 175%

scrollissue

@manekinekko . I've updated Browser Zoom setting from 100% to 175% but still not getting problem in my system as you have shown.  Weird.

**Comment by sumitparakh** [comment]
> > @sumitparakh Here with a zoom of 175%
> 
> scrollissue
> 
> @manekinekko . I've updated Browser Zoom setting from 100% to 175% but still not getting problem in my system as you have shown. Weird. It seems this problem is occurring for some specific use cases. Not sure which. Need to investigate further.
